title:              Khushi Pathak
email:              khushikpathak@gmail.com
description:        Welcome to my website
author:             Khushi Pathak
baseurl:            "/startbootstrap-clean-blog-jekyll"
url:                "https://khushipathak.github.io"

# Social Profiles
twitter_username:   
github_username:    khushipathak
facebook_username:  
instagram_username:  
linkedin_username: khushi-pathak

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
